name: Set SMTP Password Secret

on:
  push:
    branches:
      - main

jobs:
  set-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Set SMTP Password
        run: echo "::add-mask::${{ secrets.SMTP_PASSWORD }}"
        env:
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
